# Automatically listen for the hotword when Home Assistant starts.
- alias: "start hotword"
  trigger:
    platform: homeassistant
    event: start
  action:
    service: hotword_precise.listen

# Play a sound when the hotword is detected.
# Start listening for a command.
- alias: "hotword -> speech to text"
  trigger:
    platform: event
    event_type: hotword_detected
  action:
    - service: wav_aplay.play_wav
      data:
        filename: $RHASSPY_ASSISTANT/etc/wav/wakeup.wav
    - service: stt_pocketsphinx.listen

# Play a sound when recording of a command has finished.
- alias: "speech to text working"
  trigger:
    platform: event
    event_type: speech_recorded
  action:
    - service: wav_aplay.play_wav
      data:
        filename: $RHASSPY_ASSISTANT/etc/wav/command_recorded.wav

# Pass text from pocketsphinx to the intent recognizer.
- alias: "speech to text -> intent recognition"
  trigger:
    platform: event
    event_type: speech_to_text
  action:
    - service: rasa_nlu.parse
      data_template:
        message: "{{ trigger.event.data['text'] }}"
        project: rhasspy
    - service: hotword_precise.listen

# Play a sound if the intent was recognized
- alias: "known intent"
  trigger:
    platform: event
    event_type: known_intent
  action:
    - service: wav_aplay.play_wav
      data:
        filename: $RHASSPY_ASSISTANT/etc/wav/intent_recognized.wav

# Play an error sound if the intent wasn't recognized.
- alias: "unknown intent"
  trigger:
    platform: event
    event_type: unknown_intent
  action:
    - service: wav_aplay.play_wav
      data:
        filename: $RHASSPY_ASSISTANT/etc/wav/intent_not_recognized.wav
